spring.datasource.url=jdbc:postgresql://ep-small-sun-aia1wbw6-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Abdu0NUXRK6E&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Abdu0NUXRK6E

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

server.servlet.context-path=/api

# WAHA
waha.base-url=https://cloudy-waha.e4xqua.easypanel.host
waha.api-key=DH2zDGOz7KusN1UItxTI4LZxVeIVig9g
waha.session=Cloudy

# Redis (para controle bot/humano) - desabilitado localmente, só funciona no servidor Docker
spring.autoconfigure.exclude=org.springframework.boot.data.redis.autoconfigure.RedisAutoConfiguration,org.springframework.boot.data.redis.autoconfigure.RedisReactiveAutoConfiguration

# Debug temporario
logging.level.org.springframework.security=DEBUG

# JWT
jwt.secret=mecaflow-tcc-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.access-token-expiration=28800000
jwt.refresh-token-expiration=604800000
