spring.datasource.url=jdbc:postgresql://ep-small-sun-aia1wbw6-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Abdu0NUXRK6E&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Abdu0NUXRK6E

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

server.servlet.context-path=/api

# WAHA
waha.base-url=https://cloudy-waha.e4xqua.easypanel.host
waha.api-key=DH2zDGOz7KusN1UItxTI4LZxVeIVig9g
waha.session=Cloudy

# Redis (para controle bot/humano)
spring.data.redis.url=redis://default:c875c4dcf056a7f60c08@cloudy_evolution-api-redis:6379
